### ISSUE TITLE
Ability to track Dispatchable or Queueable

### ISSUE THREAD

**Issue by jamespavett** [AryeoHQ/monitored-jobs#1]
Think this would be like enhancement request, but do you think there is scope to extend this package to include the monitoring of other queueable or dispatchable tasks, such as Events?

**Comment by owenconti** [comment]
Hi @jamespavett,

AFAIK events themselves can't be queued but their listeners can. This package should already be able to monitor anything that runs through the queue system, check out an example of a queued listener:

<img width="293" alt="Screen Shot 2022-03-21 at 9 46 25 AM" src="https://user-images.githubusercontent.com/791222/159298339-cc9a71bb-6e31-4b12-acd4-e55e11136c65.png">
<img width="570" alt="Screen Shot 2022-03-21 at 9 44 59 AM" src="https://user-images.githubusercontent.com/791222/159298344-b0c050b2-eb31-4ef4-95d2-8225ee0c3daf.png">
<img width="713" alt="Screen Shot 2022-03-21 at 9 44 41 AM" src="https://user-images.githubusercontent.com/791222/159298347-367939f2-df34-43b4-bfd7-cf46b99cb1c0.png">

I'll close this issue for now, as I don't believe there's anything to do, but if you spot an issue feel free to open a new issue!
