### ISSUE TITLE
Unable to install on Laravel 9

### ISSUE THREAD

**Issue by jamespavett** [AryeoHQ/monitored-jobs#2]
I am currently unable to install this package into my Laravel 9 project.

![image](https://user-images.githubusercontent.com/10764464/159655710-0c8ccdfa-989b-4703-aaae-e864e292056a.png)

Tried clearing vendor folder etc... with no change. I just get the above error.

I would have assumed the illuminate/support dependency is serviced by laravel/framework 9.5.1.

Any help would be appreciated.

**Comment by owenconti** [comment]
Hey @jamespavett 

Thanks for pointing this out. I've updated the dependencies to support both Laravel 8 and 9.

**Comment by owenconti** [comment]
@jamespavett Follow up, I needed to republish this as a 2.0.0 release: https://github.com/AryeoHQ/monitored-jobs/releases/tag/v2.0.0

**Comment by jamespavett** [comment]
Perfect, thank you!
