### ISSUE TITLE
Track non overrided information in database

### ISSUE THREAD

**Issue by jamespavett** [AryeoHQ/monitored-jobs#4]
This is an idea for a potential enhancement, I could probably look at doing a PR but just wanted to get your thoughts.

Currently columns like max_tries, max_exceptions, timeout, retry_until are all populated as null unless the value is overridden on the job class

![image](https://user-images.githubusercontent.com/10764464/160110288-c900475c-8a90-43a0-b619-35a36ea195d1.png)

i.e. the bottom job logs max_tries 1 as I have specified the tried property in the job class

![image](https://user-images.githubusercontent.com/10764464/160110743-70e44d66-8b30-45c0-8847-0da33523c6af.png)

Instead of populating null values throughout, could we not defer to the existing values in the queue.php or horizon.php files.

queue.php could be used to derive the default retry_after values for the job

![image](https://user-images.githubusercontent.com/10764464/160110945-066915b6-847d-4480-af0e-5bf464d539dd.png)

horizon.php could be used to derive the default tries, exceptions and timeout values

![image](https://user-images.githubusercontent.com/10764464/160111113-c6c95c0e-850c-40d0-8a57-aab5721843e6.png)

Obviously the default values would only populate in the table if they aren't overridden in the job class itself.

This would allow users to see an historical log of where these default values may have changes, where currently they aren't visible.

**Comment by owenconti** [comment]
Hi @jamespavett 

If this data is possible to get, I'm all for adding it in. However, my hesitation comes where we need to support more than just Horizon. Ideally we can support at least the following:

- Sync
- Database
- Redis
- SQS

I've never seen anyone use `beanstalkd`, but ideally we could support that too.

**Comment by jamespavett** [comment]
I actually hadn't considered this so thanks for mentioning.

For most types, the values are set when running the queue:work command right? As additional arguments. I know Laravel has default values as well for when these arguments aren't supplied, but not sure if they are available programmatically.

Horizon just basically sits above this, and uses the values defined in its configuration file and passes them info the above command. Not sure if there might be a catch-all way of doing this then may accommodate all situations.

**Comment by owenconti** [comment]
@jamespavett yeah I am not sure. I tried looking through the Laravel source code for a few minutes but nothing jumped out. If you have time to dig in a bit, feel free. We'd be open to accepting a PR for it, but I can't commit time to adding support myself at this time.
